//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXH_HIOTFZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanBe
    {
        public int BanBeID { get; set; }
        public int NguoiDungID1 { get; set; }
        public int NguoiDungID2 { get; set; }
        public Nullable<System.DateTime> NgayKetBan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
