//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXH_HIOTFZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThichBaiDang
    {
        public int ThichID { get; set; }
        public int BaiDangID { get; set; }
        public int NguoiDungID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BaiDang BaiDang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
