//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXH_HIOTFZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ThongBaoID { get; set; }
        public int NguoiNhanID { get; set; }
        public int NguoiGuiID { get; set; }
        public string LoaiThongBao { get; set; }
        public string NoiDung { get; set; }
        public string Link { get; set; }
        public Nullable<bool> DaDoc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
