//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MXH_HIOTFZone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhan
    {
        public int TinNhanID { get; set; }
        public int CuocTroChuyenID { get; set; }
        public int NguoiGuiID { get; set; }
        public string NoiDungTin { get; set; }
        public string AnhUrl { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual CuocTroChuyen CuocTroChuyen { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
